POST https://flobooks.pythonanywhere.com/auth/phone/
Content-Type: application/json

{
"phone_number": "08039907188"
}



###
POST https://flobooks.pythonanywhere.com/auth/verify-phone/
Content-Type: application/json

{
"phone_number": "08039907188",
"otp": "569166"
}

###

POST https://flobooks.pythonanywhere.com/auth/send-email/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwODY5OTUzLCJpYXQiOjE3NDA4Njk2NTMsImp0aSI6ImFmNmE0NzRkNzMwNDQzODZhY2U5MjMyZThmYmJlM2FhIiwidXNlcl9pZCI6MTd9.i-25b1vhv7aWicVQdtVLsUdKVdFkIWjQk0AKOSTMrio

{
"email": "sleep1@gmail.com"
}

###

POST https://flobooks.pythonanywhere.com/auth/verify-email/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwODY5MDA1LCJpYXQiOjE3NDA4Njg3MDUsImp0aSI6IjY1OTRlY2U1MjIzYTRhMWY4MzE1MmRmNDA5MGI0MjE2IiwidXNlcl9pZCI6MTd9.M1qw36fZEQuVwGmcXBev4QWl7bJFhN-2uBmpNii5CxE

{
"verification_code": "304142"
}

###

POST https://flobooks.pythonanywhere.com/auth/passcode/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwODY5MDA1LCJpYXQiOjE3NDA4Njg3MDUsImp0aSI6IjY1OTRlY2U1MjIzYTRhMWY4MzE1MmRmNDA5MGI0MjE2IiwidXNlcl9pZCI6MTd9.M1qw36fZEQuVwGmcXBev4QWl7bJFhN-2uBmpNii5CxE

{
"passcode": "215436"
}



###

POST https://flobooks.pythonanywhere.com/auth/bvn/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNzg2MzUxLCJpYXQiOjE3NDA3ODYwNTEsImp0aSI6ImUyN2Y0YzQwNjYyYTQ2MTVhZjhmMTY5ZDcyNTBlZGFkIiwidXNlcl9pZCI6MTZ9.MwSsAN3J5-Z5DZxVBs29l6WlLkVn6yKpuWUWh8WKkUY


{
"bvn": "11111111111"
}