POST https://flobooks.pythonanywhere.com/auth/phone/
Content-Type: application/json

{
"phone_number": "08039907188"
}

###
POST http://127.0.0.1:8000/auth/phone/
Content-Type: application/json

{
"phone_number": "00000000000"
}


###
POST http://127.0.0.1:8000/auth/verify-phone/
Content-Type: application/json

{
"phone_number": "00000000000",
"otp": "989676"
}

###

POST http://127.0.0.1:8000/auth/send-email/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNzg1NTM5LCJpYXQiOjE3NDA3ODUyMzksImp0aSI6IjAzMjVhMTY1NjYzOTRiY2ZhYTc5Zjc4MGM2ZWMzM2NhIiwidXNlcl9pZCI6MTZ9.zRS9Afia9e614-7P5fqzYA1kXS7RCOI4uJ58W_t5EAI

{
"email": "sleep1@gmail.com"

}

###

POST http://127.0.0.1:8000/auth/verify-email/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNzg2MzUxLCJpYXQiOjE3NDA3ODYwNTEsImp0aSI6ImUyN2Y0YzQwNjYyYTQ2MTVhZjhmMTY5ZDcyNTBlZGFkIiwidXNlcl9pZCI6MTZ9.MwSsAN3J5-Z5DZxVBs29l6WlLkVn6yKpuWUWh8WKkUY

{
"verification_code": "183508"
}

###

POST http://127.0.0.1:8000/auth/passcode/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNzg2MzUxLCJpYXQiOjE3NDA3ODYwNTEsImp0aSI6ImUyN2Y0YzQwNjYyYTQ2MTVhZjhmMTY5ZDcyNTBlZGFkIiwidXNlcl9pZCI6MTZ9.MwSsAN3J5-Z5DZxVBs29l6WlLkVn6yKpuWUWh8WKkUY

{
"passcode": "215436"
}



###

POST http://127.0.0.1:8000/auth/bvn/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNzg2MzUxLCJpYXQiOjE3NDA3ODYwNTEsImp0aSI6ImUyN2Y0YzQwNjYyYTQ2MTVhZjhmMTY5ZDcyNTBlZGFkIiwidXNlcl9pZCI6MTZ9.MwSsAN3J5-Z5DZxVBs29l6WlLkVn6yKpuWUWh8WKkUY


{
"bvn": "11111111111"
}