POST https://flobooks.pythonanywhere.com/auth/phone/
Content-Type: application/json

{
"phone_number": "08039907188"
}

###
POST http://127.0.0.1:8000/auth/phone/
Content-Type: application/json

{
"phone_number": "11111111000"
}


###
POST http://127.0.0.1:8000/auth/verify-phone/
Content-Type: application/json

{
"phone_number": "11111111000",
"otp": "950429"
}

###

POST http://127.0.0.1:8000/auth/send-email/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTQ0NjcyLCJpYXQiOjE3Mzc5NDQzNzIsImp0aSI6ImE3ODE0YzQ5ZTM5NTQyMGY5ZDkxNmMyMDdmYmZhZTU4IiwidXNlcl9pZCI6MTN9.GBFYaBWq5i1L8p03bE6FsFI0TBD3h-_qHC6_ezW-hZw

{
"email": "david2@gmail.com"
}

###

POST http://127.0.0.1:8000/auth/verify-email/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTQ0NjcyLCJpYXQiOjE3Mzc5NDQzNzIsImp0aSI6ImE3ODE0YzQ5ZTM5NTQyMGY5ZDkxNmMyMDdmYmZhZTU4IiwidXNlcl9pZCI6MTN9.GBFYaBWq5i1L8p03bE6FsFI0TBD3h-_qHC6_ezW-hZw


{
"email": "david2@gmail.com",
"verification_code": "548610"
}

###

POST http://127.0.0.1:8000/auth/passcode/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTQ0NjcyLCJpYXQiOjE3Mzc5NDQzNzIsImp0aSI6ImE3ODE0YzQ5ZTM5NTQyMGY5ZDkxNmMyMDdmYmZhZTU4IiwidXNlcl9pZCI6MTN9.GBFYaBWq5i1L8p03bE6FsFI0TBD3h-_qHC6_ezW-hZw


{
"passcode": "215436"
}



###

POST http://127.0.0.1:8000/auth/bvn/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTQzNjY4LCJpYXQiOjE3Mzc5NDMzNjgsImp0aSI6IjhhNDIyZWE2MWQ2NzRhM2M5MjM5ZGY1MzIxMTk4ZTgxIiwidXNlcl9pZCI6MTJ9.axPJJPjOHPRZN_Ipv0_QapeepYMd_DuW3reeYg4Heb

{
"bvn": "11111111111"
}