# Generated by Django 5.0.4 on 2025-01-18 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
